[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x47505e"
blue = "0x5db3ef"
cyan = "0x51dbff"
green = "0x9bbe6e"
magenta = "0xc882dd"
red = "0xff7877"
white = "0xc4c8cf"
yellow = "0xecc286"

[colors.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Text Italic"

[font.normal]
family = "monospace"
style = "Text"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 50000

[window.padding]
x = 0
y = 0
